//  AppLink.h
//  SyncProxy
//  Copyright (c) 2014 Ford Motor Company. All rights reserved.

//AppLink
#import <AppLink/FMCJingle.h>
#import <AppLink/FMCProxyListener.h>
#import <AppLink/FMCRPCRequestFactory.h>
#import <AppLink/FMCSyncProxy.h>
#import <AppLink/FMCSyncProxyFactory.h>
#import <AppLink/FMCTTSChunkFactory.h>

//AppLink Debug
#import <AppLink/Debug/FMCConsoleController.h>
#import <AppLink/Debug/FMCDebugTool.h>
#import <AppLink/Debug/FMCSiphonServer.h>

//RPC Requests
#import <AppLink/RPC/Requests/FMCAddCommand.h>
#import <AppLink/RPC/Requests/FMCAddSubMenu.h>
#import <AppLink/RPC/Requests/FMCAlert.h>
#import <AppLink/RPC/Requests/FMCAlertManeuver.h>
#import <AppLink/RPC/Requests/FMCChangeRegistration.h>
#import <AppLink/RPC/Requests/FMCCreateInteractionChoiceSet.h>
#import <AppLink/RPC/Requests/FMCDeleteCommand.h>
#import <AppLink/RPC/Requests/FMCDeleteFile.h>
#import <AppLink/RPC/Requests/FMCDeleteInteractionChoiceSet.h>
#import <AppLink/RPC/Requests/FMCDeleteSubMenu.h>
#import <AppLink/RPC/Requests/FMCDiagnosticMessage.h>
#import <AppLink/RPC/Requests/FMCEncodedSyncPData.h>
#import <AppLink/RPC/Requests/FMCEndAudioPassThru.h>
#import <AppLink/RPC/Requests/FMCGetDTCs.h>
#import <AppLink/RPC/Requests/FMCGetVehicleData.h>
#import <AppLink/RPC/Requests/FMCListFiles.h>
#import <AppLink/RPC/Requests/FMCPerformAudioPassThru.h>
#import <AppLink/RPC/Requests/FMCPerformInteraction.h>
#import <AppLink/RPC/Requests/FMCPutFile.h>
#import <AppLink/RPC/Requests/FMCReadDID.h>
#import <AppLink/RPC/Requests/FMCRegisterAppInterface.h>
#import <AppLink/RPC/Requests/FMCResetGlobalProperties.h>
#import <AppLink/RPC/Requests/FMCScrollableMessage.h>
#import <AppLink/RPC/Requests/FMCSetAppIcon.h>
#import <AppLink/RPC/Requests/FMCSetDisplayLayout.h>
#import <AppLink/RPC/Requests/FMCSetGlobalProperties.h>
#import <AppLink/RPC/Requests/FMCSetMediaClockTimer.h>
#import <AppLink/RPC/Requests/FMCShow.h>
#import <AppLink/RPC/Requests/FMCShowConstantTBT.h>
#import <AppLink/RPC/Requests/FMCSlider.h>
#import <AppLink/RPC/Requests/FMCSpeak.h>
#import <AppLink/RPC/Requests/FMCSubscribeButton.h>
#import <AppLink/RPC/Requests/FMCSubscribeVehicleData.h>
#import <AppLink/RPC/Requests/FMCSyncPData.h>
#import <AppLink/RPC/Requests/FMCUpdateTurnList.h>
#import <AppLink/RPC/Requests/FMCUnregisterAppInterface.h>
#import <AppLink/RPC/Requests/FMCUnsubscribeButton.h>
#import <AppLink/RPC/Requests/FMCUnsubscribeVehicleData.h>

//RPC Responses
#import <AppLink/RPC/Responses/FMCAddCommandResponse.h>
#import <AppLink/RPC/Responses/FMCAddSubMenuResponse.h>
#import <AppLink/RPC/Responses/FMCAlertResponse.h>
#import <AppLink/RPC/Responses/FMCAlertManeuverResponse.h>
#import <AppLink/RPC/Responses/FMCChangeRegistrationResponse.h>
#import <AppLink/RPC/Responses/FMCCreateInteractionChoiceSetResponse.h>
#import <AppLink/RPC/Responses/FMCDeleteCommandResponse.h>
#import <AppLink/RPC/Responses/FMCDeleteFileResponse.h>
#import <AppLink/RPC/Responses/FMCDeleteInteractionChoiceSetResponse.h>
#import <AppLink/RPC/Responses/FMCDeleteSubMenuResponse.h>
#import <AppLink/RPC/Responses/FMCDiagnosticMessageResponse.h>
#import <AppLink/RPC/Responses/FMCEncodedSyncPDataResponse.h>
#import <AppLink/RPC/Responses/FMCEndAudioPassThruResponse.h>
#import <AppLink/RPC/Responses/FMCGenericResponse.h>
#import <AppLink/RPC/Responses/FMCGetDTCsResponse.h>
#import <AppLink/RPC/Responses/FMCGetVehicleDataResponse.h>
#import <AppLink/RPC/Responses/FMCListFilesResponse.h>
#import <AppLink/RPC/Responses/FMCPerformAudioPassThruResponse.h>
#import <AppLink/RPC/Responses/FMCPerformInteractionResponse.h>
#import <AppLink/RPC/Responses/FMCPutFileResponse.h>
#import <AppLink/RPC/Responses/FMCReadDIDResponse.h>
#import <AppLink/RPC/Responses/FMCRegisterAppInterfaceResponse.h>
#import <AppLink/RPC/Responses/FMCResetGlobalPropertiesResponse.h>
#import <AppLink/RPC/Responses/FMCScrollableMessageResponse.h>
#import <AppLink/RPC/Responses/FMCSetAppIconResponse.h>
#import <AppLink/RPC/Responses/FMCSetDisplayLayoutResponse.h>
#import <AppLink/RPC/Responses/FMCSetGlobalPropertiesResponse.h>
#import <AppLink/RPC/Responses/FMCSetMediaClockTimerResponse.h>
#import <AppLink/RPC/Responses/FMCShowConstantTBTResponse.h>
#import <AppLink/RPC/Responses/FMCShowResponse.h>
#import <AppLink/RPC/Responses/FMCSliderResponse.h>
#import <AppLink/RPC/Responses/FMCSpeakResponse.h>
#import <AppLink/RPC/Responses/FMCSubscribeButtonResponse.h>
#import <AppLink/RPC/Responses/FMCSubscribeVehicleDataResponse.h>
#import <AppLink/RPC/Responses/FMCSyncPDataResponse.h>
#import <AppLink/RPC/Responses/FMCUpdateTurnListResponse.h>
#import <AppLink/RPC/Responses/FMCUnregisterAppInterfaceResponse.h>
#import <AppLink/RPC/Responses/FMCUnsubscribeButtonResponse.h>
#import <AppLink/RPC/Responses/FMCUnsubscribeVehicleDataResponse.h>

//RPC Notifications
#import <AppLink/RPC/Notifications/FMCOnAppInterfaceUnregistered.h>
#import <AppLink/RPC/Notifications/FMCOnAudioPassThru.h>
#import <AppLink/RPC/Notifications/FMCOnButtonEvent.h>
#import <AppLink/RPC/Notifications/FMCOnButtonPress.h>
#import <AppLink/RPC/Notifications/FMCOnCommand.h>
#import <AppLink/RPC/Notifications/FMCOnDriverDistraction.h>
#import <AppLink/RPC/Notifications/FMCOnEncodedSyncPData.h>
#import <AppLink/RPC/Notifications/FMCOnHashChange.h>
#import <AppLink/RPC/Notifications/FMCOnHMIStatus.h>
#import <AppLink/RPC/Notifications/FMCOnKeyboardInput.h>
#import <AppLink/RPC/Notifications/FMCOnLanguageChange.h>
#import <AppLink/RPC/Notifications/FMCOnPermissionsChange.h>
#import <AppLink/RPC/Notifications/FMCOnSyncPData.h>
#import <AppLink/RPC/Notifications/FMCOnSystemRequest.h>
#import <AppLink/RPC/Notifications/FMCOnVehicleData.h>
#import <AppLink/RPC/Notifications/FMCOnTBTClientState.h>
#import <AppLink/RPC/Notifications/FMCOnTouchEvent.h>
#import <AppLink/RPC/Notifications/FMCOnVehicleData.h>

//RPC Structs
#import <AppLink/RPC/Structs/FMCAirbagStatus.h>
#import <AppLink/RPC/Structs/FMCAudioPassThruCapabilities.h>
#import <AppLink/RPC/Structs/FMCBeltStatus.h>
#import <AppLink/RPC/Structs/FMCBodyInformation.h>
#import <AppLink/RPC/Structs/FMCButtonCapabilities.h>
#import <AppLink/RPC/Structs/FMCChoice.h>
#import <AppLink/RPC/Structs/FMCClusterModeStatus.h>
#import <AppLink/RPC/Structs/FMCDeviceInfo.h>
#import <AppLink/RPC/Structs/FMCDeviceStatus.h>
#import <AppLink/RPC/Structs/FMCDIDResult.h>
#import <AppLink/RPC/Structs/FMCDisplayCapabilities.h>
#import <AppLink/RPC/Structs/FMCECallInfo.h>
#import <AppLink/RPC/Structs/FMCEmergencyEvent.h>
#import <AppLink/RPC/Structs/FMCGPSData.h>
#import <AppLink/RPC/Structs/FMCHeadLampStatus.h>
#import <AppLink/RPC/Structs/FMCHMIPermissions.h>
#import <AppLink/RPC/Structs/FMCImage.h>
#import <AppLink/RPC/Structs/FMCKeyboardProperties.h>
#import <AppLink/RPC/Structs/FMCMenuParams.h>
#import <AppLink/RPC/Structs/FMCMyKey.h>
#import <AppLink/RPC/Structs/FMCParameterPermissions.h>
#import <AppLink/RPC/Structs/FMCPermissionItem.h>
#import <AppLink/RPC/Structs/FMCPresetBankCapabilities.h>
#import <AppLink/RPC/Structs/FMCSingleTireStatus.h>
#import <AppLink/RPC/Structs/FMCSoftButton.h>
#import <AppLink/RPC/Structs/FMCSoftButtonCapabilities.h>
#import <AppLink/RPC/Structs/FMCStartTime.h>
#import <AppLink/RPC/Structs/FMCSyncMsgVersion.h>
#import <AppLink/RPC/Structs/FMCTextField.h>
#import <AppLink/RPC/Structs/FMCTireStatus.h>
#import <AppLink/RPC/Structs/FMCTTSChunk.h>
#import <AppLink/RPC/Structs/FMCTurn.h>
#import <AppLink/RPC/Structs/FMCVehicleDataResult.h>
#import <AppLink/RPC/Structs/FMCVehicleType.h>
#import <AppLink/RPC/Structs/FMCVrHelpItem.h>

//RPC Enums
#import <AppLink/RPC/Enums/FMCAppHMIType.h>
#import <AppLink/RPC/Enums/FMCAppInterfaceUnregisteredReason.h>
#import <AppLink/RPC/Enums/FMCAudioStreamingState.h>
#import <AppLink/RPC/Enums/FMCAudioType.h>
#import <AppLink/RPC/Enums/FMCBitsPerSample.h>
#import <AppLink/RPC/Enums/FMCButtonEventMode.h>
#import <AppLink/RPC/Enums/FMCButtonName.h>
#import <AppLink/RPC/Enums/FMCButtonPressMode.h>
#import <AppLink/RPC/Enums/FMCCarModeStatus.h>
#import <AppLink/RPC/Enums/FMCECallConfirmationStatus.h>
#import <AppLink/RPC/Enums/FMCCharacterSet.h>
#import <AppLink/RPC/Enums/FMCCompassDirection.h>
#import <AppLink/RPC/Enums/FMCComponentVolumeStatus.h>
#import <AppLink/RPC/Enums/FMCDimension.h>
#import <AppLink/RPC/Enums/FMCDisplayType.h>
#import <AppLink/RPC/Enums/FMCDriverDistractionState.h>
#import <AppLink/RPC/Enums/FMCDeviceLevelStatus.h>
#import <AppLink/RPC/Enums/FMCEmergencyEventType.h>
#import <AppLink/RPC/Enums/FMCFileType.h>
#import <AppLink/RPC/Enums/FMCFuelCutoffStatus.h>
#import <AppLink/RPC/Enums/FMCGlobalProperty.h>
#import <AppLink/RPC/Enums/FMCHMILevel.h>
#import <AppLink/RPC/Enums/FMCHmiZoneCapabilities.h>
#import <AppLink/RPC/Enums/FMCIgnitionStableStatus.h>
#import <AppLink/RPC/Enums/FMCIgnitionStatus.h>
#import <AppLink/RPC/Enums/FMCImageType.h>
#import <AppLink/RPC/Enums/FMCInteractionMode.h>
#import <AppLink/RPC/Enums/FMCKeyboardEvent.h>
#import <AppLink/RPC/Enums/FMCKeyboardLayout.h>
#import <AppLink/RPC/Enums/FMCKeypressMode.h>
#import <AppLink/RPC/Enums/FMCLanguage.h>
#import <AppLink/RPC/Enums/FMCMaintenanceModeStatus.h>
#import <AppLink/RPC/Enums/FMCMediaClockFormat.h>
#import <AppLink/RPC/Enums/FMCPermissionStatus.h>
#import <AppLink/RPC/Enums/FMCPowerModeQualificationStatus.h>
#import <AppLink/RPC/Enums/FMCPowerModeStatus.h>
#import <AppLink/RPC/Enums/FMCPrimaryAudioSource.h>
#import <AppLink/RPC/Enums/FMCPRNDL.h>
#import <AppLink/RPC/Enums/FMCResult.h>
#import <AppLink/RPC/Enums/FMCRPCMessageType.h>
#import <AppLink/RPC/Enums/FMCSamplingRate.h>
#import <AppLink/RPC/Enums/FMCScreenParams.h>
#import <AppLink/RPC/Enums/FMCSoftButtonType.h>
#import <AppLink/RPC/Enums/FMCSpeechCapabilities.h>
#import <AppLink/RPC/Enums/FMCSystemAction.h>
#import <AppLink/RPC/Enums/FMCSystemContext.h>
#import <AppLink/RPC/Enums/FMCTBTState.h>
#import <AppLink/RPC/Enums/FMCTextAlignment.h>
#import <AppLink/RPC/Enums/FMCTextFieldName.h>
#import <AppLink/RPC/Enums/FMCTimerMode.h>
#import <AppLink/RPC/Enums/FMCTriggerSource.h>
#import <AppLink/RPC/Enums/FMCUpdateMode.h>
#import <AppLink/RPC/Enums/FMCVehicleDataActiveStatus.h>
#import <AppLink/RPC/Enums/FMCVehicleDataEventStatus.h>
#import <AppLink/RPC/Enums/FMCVehicleDataNotificationStatus.h>
#import <AppLink/RPC/Enums/FMCVehicleDataResultCode.h>
#import <AppLink/RPC/Enums/FMCVehicleDataStatus.h>
#import <AppLink/RPC/Enums/FMCVehicleDataType.h>
#import <AppLink/RPC/Enums/FMCVrCapabilities.h>
#import <AppLink/RPC/Enums/FMCWarningLightStatus.h>
#import <AppLink/RPC/Enums/FMCWiperStatus.h>